version: "3.9"

services:
    ini-node:
        image: node:20-alpine
        container_name: ats-node
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        ports:
            - "5001:5001"
        depends_on:
            - ini-db
        command: ["npm", "run", "dev"]
        networks:
            - ini-network

    ini-db:
        image: mariadb:latest
        container_name: ini-db
        volumes:
            - ini_db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=ats
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"
        networks:
            - ini-network

volumes:
    ini_db_data:

networks:
    ini-network:
        driver: bridge
